apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: ewsvwb9ms-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-253bd3e2f0.hdtj.p3.openshiftapps.com/rhtap/rhtap-qe:45cd9ab1021c7d5b5042cf528356379334ce0d8a@sha256:4c1538576a07c2afd51167c726f53c5b8a5248d5b7140e1951e9d5208c281136
          name: container-image
